### ISSUE TITLE
A good reference for your "Anti" lists

### ISSUE THREAD

**Issue by gorshco** [Cybo1927/Hosts#68]
https://github.com/googlehosts/hosts/blob/master/hosts-files/hosts

**Comment by Cybo1927** [comment]
Thanks! Did you want me to make them work better with dns blocking (right now most of it is based around AdGuard products)?

**Comment by gorshco** [comment]
No, I thought you can benefit from comparing your "Anti" hosts to the hosts in the list I've linked, it's really well maintained and thoroughly covering most big companies...

**Comment by Cybo1927** [comment]
Okay, thanks!

Note: It was just a question as I want feedback on if I should support DNS blocking from things like Pi-Hole which is less advance than AdGuard Home.

**Comment by gorshco** [comment]
That's entirely up to you as it will require you to maintain more lists. :)
