### ISSUE TITLE
Use of wildcard * in hosts files

### ISSUE THREAD

**Issue by mozdevcontrib** [Cybo1927/Hosts#72]
## Issue Description

The `*` wildcard does not function in hosts files.

## Issue Details

- **List:**
  - Anti Location

1. I was browsing through `https://FilterLists.com` to see what's new in the world of filters / filter creators. I quickly glanced through your Anti Location filter, so I cannot say if you've used the `*` wildcard in any other hosts files you may have; however, as it currently exists, "Anti Location" contains a hosts file within it. As it currently exists (copied/pasted directly below) it uses the `*` wildcard as a suffix for a few rules:

> 0.0.0.0 locuslabs.com
0.0.0.0 api.mapbox.com
0.0.0.0 mapbox.com
0.0.0.0 maps.google.com
0.0.0.0 mapquest.com
0.0.0.0 maps.yahoo.com
0.0.0.0 mapway.com
0.0.0.0 ud-prd.geohawk.co.uk
0.0.0.0 geohawk.co.uk
0.0.0.0 openstreetmap.*
0.0.0.0 openweathermap.*
0.0.0.0 maps.randmcnally.com
0.0.0.0 viamichelin.com
0.0.0.0 wikimapia.org
0.0.0.0 wego.here.com
0.0.0.0 here.com
0.0.0.0 map.baidu.com
0.0.0.0 map.qq.com
0.0.0.0 bhuvan-app1.nrsc.gov.in
0.0.0.0 geoportail.gouv.fr
0.0.0.0 waze.com
0.0.0.0 destinations.maps.me
0.0.0.0 maps.me
0.0.0.0 mapswith.me
0.0.0.0 osmand.net
0.0.0.0 ditu.amap.com
0.0.0.0 amap.com
0.0.0.0 sygic.com
0.0.0.0 copilotgps.com
0.0.0.0 mapout.app
0.0.0.0 gurumaps.app
0.0.0.0 gpsmycity.com
0.0.0.0 scoutgps.com
0.0.0.0 scoutgpslink.com
0.0.0.0 mytopo.com
0.0.0.0 topozone.com
0.0.0.0 gpsandtrack.com
0.0.0.0 secure.accutracking.com
0.0.0.0 accutracking.com
0.0.0.0 logistimatics.com
0.0.0.0 teletracnavman.com
0.0.0.0 quartix.com
0.0.0.0 liveviewgps.com
0.0.0.0 routetracko.com
0.0.0.0 linxup.com
0.0.0.0 navixy.com
0.0.0.0 trackersystems.net
0.0.0.0 gpstrackit.com
0.0.0.0 amcrestgpstracker.com
0.0.0.0 amcrestgps.net
0.0.0.0 gpstrackservices.com
0.0.0.0 gpsphonetracker.org
0.0.0.0 trackyourtruck.com
0.0.0.0 budgetgps.com
0.0.0.0 trymobilespy.com
0.0.0.0 gpstrackerservice.com
0.0.0.0 gpswox.com
0.0.0.0 traccar.org
0.0.0.0 gotrack.com
0.0.0.0 trackrtalk.com
0.0.0.0 phonetracker-geek.com
0.0.0.0 sat-gps-tracker.com
0.0.0.0 gps-server.net
0.0.0.0 mspy.com
0.0.0.0 gpsinsight.com
0.0.0.0 mobiletrackingandconsulting.com
0.0.0.0 awaregps.com
0.0.0.0 btracking.com
0.0.0.0 geotrack24.com
0.0.0.0 intouchgps.com
0.0.0.0 pitneybowes.com
0.0.0.0 sas.com
0.0.0.0 pivvot.com
0.0.0.0 db-ip.com
0.0.0.0 api-maps.yandex.*
0.0.0.0 maps.yandex.*
0.0.0.0 bestmaps.ru
0.0.0.0 2gis.ua
0.0.0.0 map.meta.ua
0.0.0.0 map.i.ua
0.0.0.0 infoportal.ua
0.0.0.0 maps-world.ru
0.0.0.0 kartaonline.com
0.0.0.0 satellite-maps.ru
0.0.0.0 liveuamap.com
0.0.0.0 1maps.ru
0.0.0.0 earth3dmap.com
0.0.0.0 maps.sputnik.ru
0.0.0.0 gisfile.com
0.0.0.0 world-maps.pro
0.0.0.0 russia-karta.ru
0.0.0.0 api.alpify.com
0.0.0.0 alpify.com
0.0.0.0 life360.com
0.0.0.0 location-inference-westus.cloudapp.net
0.0.0.0 inference.location.live.net
0.0.0.0 maps.windows.com
0.0.0.0 fysical.com
0.0.0.0 beaconinspace.com
0.0.0.0 weatherops.com
0.0.0.0 onelouder.com
0.0.0.0 loc.nine.com.au
0.0.0.0 geo1.weatherzone.com.au
0.0.0.0 geo2.weatherzone.com.au
0.0.0.0 geo3.weatherzone.com.au
0.0.0.0 geo4.weatherzone.com.au
0.0.0.0 ip-adress.com
0.0.0.0 ipaddress.com
0.0.0.0 foursquare.com
0.0.0.0 api.telogis.eu
0.0.0.0 spotlight.telogis.com
0.0.0.0 trips.telogis.com
0.0.0.0 mobilecore-dist.flows.telogis.com
0.0.0.0 static.telogis.com
0.0.0.0 login.platform.telogis.com
0.0.0.0 geo-pro.beatport.com
0.0.0.0 geoip.youversionapi.com
0.0.0.0 geoip.*

- **Browser:**
  - N/A

## ~Possible~ fix:

> 0.0.0.0 locuslabs.com
0.0.0.0 api.mapbox.com
0.0.0.0 mapbox.com
0.0.0.0 maps.google.com
0.0.0.0 mapquest.com
0.0.0.0 maps.yahoo.com
0.0.0.0 mapway.com
0.0.0.0 ud-prd.geohawk.co.uk
0.0.0.0 geohawk.co.uk
0.0.0.0 openstreetmap.
0.0.0.0 openweathermap.
0.0.0.0 maps.randmcnally.com
0.0.0.0 viamichelin.com
0.0.0.0 wikimapia.org
0.0.0.0 wego.here.com
0.0.0.0 here.com
0.0.0.0 map.baidu.com
0.0.0.0 map.qq.com
0.0.0.0 bhuvan-app1.nrsc.gov.in
0.0.0.0 geoportail.gouv.fr
0.0.0.0 waze.com
0.0.0.0 destinations.maps.me
0.0.0.0 maps.me
0.0.0.0 mapswith.me
0.0.0.0 osmand.net
0.0.0.0 ditu.amap.com
0.0.0.0 amap.com
0.0.0.0 sygic.com
0.0.0.0 copilotgps.com
0.0.0.0 mapout.app
0.0.0.0 gurumaps.app
0.0.0.0 gpsmycity.com
0.0.0.0 scoutgps.com
0.0.0.0 scoutgpslink.com
0.0.0.0 mytopo.com
0.0.0.0 topozone.com
0.0.0.0 gpsandtrack.com
0.0.0.0 secure.accutracking.com
0.0.0.0 accutracking.com
0.0.0.0 logistimatics.com
0.0.0.0 teletracnavman.com
0.0.0.0 quartix.com
0.0.0.0 liveviewgps.com
0.0.0.0 routetracko.com
0.0.0.0 linxup.com
0.0.0.0 navixy.com
0.0.0.0 trackersystems.net
0.0.0.0 gpstrackit.com
0.0.0.0 amcrestgpstracker.com
0.0.0.0 amcrestgps.net
0.0.0.0 gpstrackservices.com
0.0.0.0 gpsphonetracker.org
0.0.0.0 trackyourtruck.com
0.0.0.0 budgetgps.com
0.0.0.0 trymobilespy.com
0.0.0.0 gpstrackerservice.com
0.0.0.0 gpswox.com
0.0.0.0 traccar.org
0.0.0.0 gotrack.com
0.0.0.0 trackrtalk.com
0.0.0.0 phonetracker-geek.com
0.0.0.0 sat-gps-tracker.com
0.0.0.0 gps-server.net
0.0.0.0 mspy.com
0.0.0.0 gpsinsight.com
0.0.0.0 mobiletrackingandconsulting.com
0.0.0.0 awaregps.com
0.0.0.0 btracking.com
0.0.0.0 geotrack24.com
0.0.0.0 intouchgps.com
0.0.0.0 pitneybowes.com
0.0.0.0 sas.com
0.0.0.0 pivvot.com
0.0.0.0 db-ip.com
0.0.0.0 api-maps.yandex.
0.0.0.0 maps.yandex.
0.0.0.0 bestmaps.ru
0.0.0.0 2gis.ua
0.0.0.0 map.meta.ua
0.0.0.0 map.i.ua
0.0.0.0 infoportal.ua
0.0.0.0 maps-world.ru
0.0.0.0 kartaonline.com
0.0.0.0 satellite-maps.ru
0.0.0.0 liveuamap.com
0.0.0.0 1maps.ru
0.0.0.0 earth3dmap.com
0.0.0.0 maps.sputnik.ru
0.0.0.0 gisfile.com
0.0.0.0 world-maps.pro
0.0.0.0 russia-karta.ru
0.0.0.0 api.alpify.com
0.0.0.0 alpify.com
0.0.0.0 life360.com
0.0.0.0 location-inference-westus.cloudapp.net
0.0.0.0 inference.location.live.net
0.0.0.0 maps.windows.com
0.0.0.0 fysical.com
0.0.0.0 beaconinspace.com
0.0.0.0 weatherops.com
0.0.0.0 onelouder.com
0.0.0.0 loc.nine.com.au
0.0.0.0 geo1.weatherzone.com.au
0.0.0.0 geo2.weatherzone.com.au
0.0.0.0 geo3.weatherzone.com.au
0.0.0.0 geo4.weatherzone.com.au
0.0.0.0 ip-adress.com
0.0.0.0 ipaddress.com
0.0.0.0 foursquare.com
0.0.0.0 api.telogis.eu
0.0.0.0 spotlight.telogis.com
0.0.0.0 trips.telogis.com
0.0.0.0 mobilecore-dist.flows.telogis.com
0.0.0.0 static.telogis.com
0.0.0.0 login.platform.telogis.com
0.0.0.0 geo-pro.beatport.com
0.0.0.0 geoip.youversionapi.com
0.0.0.0 geoip.

✌🏼Peace,
~ intr0
`https://iosprivacy.com/`

**Comment by Cybo1927** [comment]
I honestly don't see the problem with using wildcards, from my understanding it works in uBlock Origin, AdGuard, AdGuard Home, Adblock Plus, etc.

What exactly does it not work in?

**Comment by mozdevcontrib** [comment]
As a hosts file, just as you've designed that part of your filter. Say, for example, someone chose to use that section as an addition to (x) or (y) etc hosts file they use for their workstation. Wildcard so do not work. Moreover, using that filter in any other way as you've just illustrated - AdGuard, uBlock Origin, etc. - makes that wildcard unnecessary. It's unnecessary in a hosts format used in an "adblocking" extension just as it's unnecessary in an "adblock" style formatted list - as the end character for any rule. Simply use the `.` not `.*`. Using it breaks the functionality for anyone using the hosts section as part of their workstation's hosts file and isn't necessary for use in any other way.

~intr0 Ⓐ Sent from ProtonMail Professional

**Comment by Cybo1927** [comment]
Thank you for pointing this out; I didn't know it wasn't necessary. I will work on changing all my filters to replace the ".*" with "."

Does this same type of thing apply to "*." (e.g. *.tracker.com)?

**Comment by mozdevcontrib** [comment]
Apologies for the delay; you're welcome.

Something like `*.tracker.com` would depend on context - if a hosts file, then definitely yes; it's better to use sub domains in that case. For "adblock" type filters, then context matters again, except when wanting to cover all sub domains of `tracker.com` with one `||tracker.com` rule. Otherwise, it's fine.

~intr0 Ⓐ Sent from ProtonMail Professional

**Comment by Cybo1927** [comment]
Okay, thanks!

My "Hosts" file is my old and basic understanding of the syntax's from almost 2 years ago now (when I was dumb and used AdBlock Plus - it was also my first attempt at making a host file) so I feel it's time to maybe rewrite all the lists.

**Comment by mozdevcontrib** [comment]
I've not actually used them in my workstation's /etc/hosts; however I'm more than happy to do so. I'll add them later today when I begin my work trimming dead hosts from my on my own filters.
