### ISSUE TITLE
Domain deletion

### ISSUE THREAD

**Issue by MarcinCz83** [Cybo1927/Hosts#73]
## Issue Description

- klebud.pl

## Details

- **List:**
  - 
https://github.com/Cybo1927/Hosts/blob/master/Hosts

**Comment by Cybo1927** [comment]
![image](https://user-images.githubusercontent.com/39284087/85879077-40b2f180-b7c9-11ea-9ca7-907a0ae93fbb.png)

Can you please tell me what the domain is for before I unblock it?

**Comment by MarcinCz83** [comment]
Sorry :)
https://kelbud.pl

pt., 26 cze 2020 o 18:23 Cybo1927 <notifications@github.com> napisał(a):

**Comment by Cybo1927** [comment]
Thanks! I'll update my lists momentarily. If you find any other problems with my lists please feel free to let me know :)

**Comment by MarcinCz83** [comment]
Thanks!  :)

pt., 26 cze 2020 o 18:26 Cybo1927 <notifications@github.com> napisał(a):
