### ISSUE TITLE
Anti Tiktok

### ISSUE THREAD

**Issue by Quorum75** [Cybo1927/Hosts#74]
## Issue Description
It is more a request than an issue. Could we get an “Anti Tiktok” Host?

All Tiktok ring home links. 

## Details
New Anti Tiktok Host

- **List:**
Anti Tiktok Host

Thanks!

**Comment by Cybo1927** [comment]
Will do when I get some free time, thanks for the request!

**Comment by Quorum75** [comment]
Much appreciated thank you.
