### ISSUE TITLE
Question about Host

### ISSUE THREAD

**Issue by Quorum75** [Cybo1927/Hosts#76]
Sorry I did not known where to ask this question. 

What is the difference between your Host file and the one from Steven Black? 
https://github.com/StevenBlack/hosts

Thanks

**Comment by Cybo1927** [comment]
What exactly are you asking? They're both hosts files but Steven Black's is written in a traditional host format (0.0.0.0/127.0.0.1) where mine is written in the more advanced adblock syntax using `||`. My list is able to be smaller because of the syntax difference, say you wanna block doubleclick.net (Google ads), the traditional syntax would have to find the specific url for each site, so if you wanna block it using traditional syntax you'll have hundreds of domains like `example1.fls.doubleclick.net` and `example2.fls.doubleclick.net` etc. whereas the adblock syntax I can block *all* doubleclick domains with `||doubleclick.net^`

**Comment by Quorum75** [comment]
Thanks very much. It is very instructive.
So, I guess you make a difference between accessing a domain like Instagram et Instagram Analytics domain? Or all Instagram domains are blocked?

**Comment by Cybo1927** [comment]
All Instagram analytic domains should be blocked, just a different way to block them.

> I tried both Hosts and the results are very different. I don't why but I get more domains blocked, especially analytics, when using SB. BTW I'm using AG Pro.

I'm sure you get more domains blocked the amount of unique domains is probably higher than what's in my list. My list is just an extra layer of security to block ads, trackers, malware, tracking cookies, etc. that other hosts/filter lists might miss.

**Comment by Quorum75** [comment]
Unfortunately for some reasons and after multiple tests, I found out that when something gets blocked it does not appear in AG dashboard. Then, I can whitelist some legit requests. 

With your host activated access to Instagram for instance is just impossible and I don't see what is request is being blocked. 

Nevertheless, I am using the Anti ones which are perfect.

**Comment by Cybo1927** [comment]
>Unfortunately for some reasons and after multiple tests, I found out that when something gets blocked it does not appear in AG dashboard. Then, I can whitelist some legit requests.

I believe AdGuard is broken right now, I don't know what's happening but I opened this request `https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1675` and it's also not working on my schools Chromebook

>With your host activated access to Instagram for instance is just impossible and I don't see what is request is being blocked.

>Nevertheless, I am using the Anti ones which are perfect.

My main hosts file breaks Instagram? Or is it the Anti Facebook?

**Comment by Quorum75** [comment]
Regarding AG, as mentioned I am using AG Pro on iOS and AG for macOS so I don't know about browser extension. Regarding both AG applications I am using they are working perfectly fine. No issue here. 

Also, I am referring to AG Activity dashboard you have on iOS. 

Regarding Instagram, I am sorry to say but it does not work with your Host. Here are all the DNS filters I use. ![image](https://user-images.githubusercontent.com/49731083/90291407-27046100-de80-11ea-86ab-d11f99a03287.png)

If I add your host, and obviously I deactivate Steven'one, access to Instagram beaks and there is no blocked links in the dashboard. 
If I deactivate your host and activate Steven'one then access to Instagram is authorized, hence my conclusion about your host.

**Comment by Cybo1927** [comment]
I don't have an Apple device to test this out with, can you try to whitelist things to help me find what's breaking it? Login works on my desktop (Solus 4.1, Linux) and my Google Pixel 3

My best guess is I'm blocking an IP address that I shouldn't be, sometimes I've found I mistakenly put experimental filters into my hosts before I should (something I've worked on)

**Comment by Quorum75** [comment]
I though you said you had an iPad. However as mentioned, there is no blocked domain in AG blocked list. This why I can't whitelist it. I have no visibility of what's wrong.

**Comment by Cybo1927** [comment]
> I though you said you had an iPad.

I have an iPad Mini 2 from 2013-2014 and it's not on the newest versions of iOS. I have no problems with it; I just tested and I have no problems.

>However as mentioned, there is no blocked domain in AG blocked list. This why I can't whitelist it. I have no visibility of what's wrong.

If you're using the app please try the website and report back, I'll get the domains I can and see if there's anything I can do to test whitelisting urls

**Comment by Cybo1927** [comment]
Okay, I've just updated my hosts please update and retry logging in to Instagram

**Comment by Quorum75** [comment]
Yes it works fine now 👍🏻
