### ISSUE TITLE
Domains that shouldn’t be blocked in Host

### ISSUE THREAD

**Issue by Quorum75** [Cybo1927/Hosts#78]
+gsp-ssl.ls.apple.com

Allow location search when adding an event into an agenda application.

**Comment by Quorum75** [comment]
+api-glb-fra.smoot.apple.com

Added to allow list in order to load Apple News Widget.

**Comment by Quorum75** [comment]
+graph.microsoft.com

Allow access to Boxcryptor / OneDrive

**Comment by Cybo1927** [comment]
Thanks, working on an update right now

**Comment by Quorum75** [comment]
There is also an issue with Microsoft News widget that doesn't load fresh news but I cannot figure out which domain. 

Also, many links are broken within Forbes website.

**Comment by Cybo1927** [comment]
"HubSpot is an American developer and marketer of software products for inbound marketing, sales, and customer service. It was founded by Brian Halligan and Dharmesh Shah in 2006." https://en.wikipedia.org/wiki/HubSpot

That's why it's blocked, I'll look at fixing it without unblocking ads thanks for letting me know!

**Comment by Quorum75** [comment]
https://councils.forbes.com/terms/ 

![image](https://user-images.githubusercontent.com/49731083/91176555-bc0a2400-e6e2-11ea-97c9-915c868141a1.png)

If you click on "Do I qualify" at the bottom of the page, you should end up on this page: 

https://councils.forbes.com/qualify/?hsCtaTracking=76875423-8445-4a3c-b913-6e81c498b19e%7C70774900-ac6c-41b1-9a5b-e83178bc9a4e

![image](https://user-images.githubusercontent.com/49731083/91176719-fa074800-e6e2-11ea-9326-872bc8906c65.png)

But instead you end up on 

https://cta-service-cms2.hubspot.com/ctas/v2/public/cs/c/?cta_guid=70774900-ac6c-41b1-9a5b-e83178bc9a4e&placement_guid=76875423-8445-4a3c-b913-6e81c498b19e&portal_id=4846748&canon=http%3A%2F%2Fcouncils.forbes.com%2Fterms%2F&redirect_url=APefjpE0pg6DwCPBVTzhfSIlgBq_DpRdurLT1affTocDgoF-ezM5gS-4-UHhebVtjgd2YUEcqrVMR0VuMsej-BILTxhUmOHsFFHZ6fm_aXOvYjcXPsavmvznRl4FlMJy95vreBgYEP2z&click=901482cb-6cde-4489-9bc5-2c32e896c445&hsutk=c7a000001b3511131e8c017425b073f5&signature=AAH58kEMiw7uqSVkBaahgFRm9w0y2NN5kQ&pageId=26637955154
![image](https://user-images.githubusercontent.com/49731083/91176852-2622c900-e6e3-11ea-9675-35e9305e9d1a.png)

**Comment by Quorum75** [comment]
BTW when I am talking about MS News widget I am referring to this iOS application. 

https://apps.apple.com/us/app/microsoft-news/id945416273

**Comment by Quorum75** [comment]
+ipfind.co

Allow access to Weather Forecast application. 

https://apps.apple.com/us/app/weather-weather-forecast/id1363846787

**Comment by Cybo1927** [comment]
Thanks for all of this! And, the Hubspot thing will be fixed before too long, you should also bring it up in either uBO or AdGuard Extension issues. That's a tracker and it's possible they could do something about it.

**Comment by Quorum75** [comment]
Apple Store Issue. 

It is impossible to write a review. 
Unfortunately AG Activity does not show anything. 
However when you deactivate the Host you can write an application review. 
So there is something in the Host that prevents it but I don't know what.

**Comment by Cybo1927** [comment]
I'll test

**Comment by Quorum75** [comment]
> you should also bring it up in either uBO or AdGuard Extension issues. That's a tracker and it's possible they could do something about it.

uBO or AdGuard Extension? 
What's uBO?
Why is it related here?

**Comment by Cybo1927** [comment]
Because you have this problem, it might be fixable on desktop (and Firefox Android) through a scriptlet

**Comment by Quorum75** [comment]
All issues mentioned here are exclusively on iOS. I am only using Safari and AG Pro (Safari and DNS protection) on iOS. 
Also, I solved my problem by adding cdn2.hubspot.net to the DNS Allow List.

**Comment by Quorum75** [comment]
BTW all domains I mentioned are in my DNS Allow List. Can you please tell me the one you are fixing in your Host then I can remove them. 
For instance a thumb up on the post?

**Comment by Cybo1927** [comment]
Yeah, I'll make sure to do that. Gonna update again right now

**Comment by Quorum75** [comment]
+jobs.lever.co

White list website

**Comment by Quorum75** [comment]
Login to MD SwiftKey is not possible. However no track of blocked domains. 

https://apps.apple.com/us/app/microsoft-swiftkey-keyboard/id911813648

**Comment by Cybo1927** [comment]
> Login to MS SwiftKey is not possible. However no track of blocked domains.
> 
> https://apps.apple.com/us/app/microsoft-swiftkey-keyboard/id911813648

Even with everything turned off it still doesn't work for me, I dunno what to do for this

**Comment by Quorum75** [comment]
> > Login to MS SwiftKey is not possible. However no track of blocked domains.
> 
> > 
> 
> > https://apps.apple.com/us/app/microsoft-swiftkey-keyboard/id911813648
> 
> 
> 
> Even with everything turned off it still doesn't work for me, I dunno what to do for this

I found it! 

users-auth.touchtype-fluency.com

**Comment by Quorum75** [comment]
+www.accenture.com

Access to website is blocked. Please whitelist. 
Question why are you blocking many legit website like this one?

**Comment by Cybo1927** [comment]
> +www.accenture.com
> 
> Access to website is blocked. Please whitelist.
> Question why are you blocking many legit website like this one?

Most of the legit domains that have been blocked are from when I first started writing my hosts file all the way back in 2018 and just blocked domains that didn't need to run on third-party sites without checking what they were

**Comment by Quorum75** [comment]
You might want to check the screen shot of AG AllowList I sent you. The sites are legit (iTunes, Tumblr, Reddit...) and needs to be with whitelisted in order to get iOS working. Cheers

**Comment by Quorum75** [comment]
+gs.apple.com

Must be whitelisted in order to be able to update iOS.

**Comment by Quorum75** [comment]
If I may, you should look at Apple and Instagram domains because the Host file breaks many functionalities. Thanks.

**Comment by Cybo1927** [comment]
Will do, just slow because of school work so sorry about that

**Comment by Quorum75** [comment]
No worries. School must be first priority. Good luck.

**Comment by Quorum75** [comment]
+cognito-identity.eu-west-1.amazonaws.com

Allow access to legit iOS ISP app 

https://apps.apple.com/us/app/espace-client-bouygues-telecom/id422590767

**Comment by Quorum75** [comment]
+api-auth-mobile.hootsuite.com

Allow Access to Hoosuite iOS app. 

https://apps.apple.com/us/app/hootsuite-social-media-tools/id341249709

**Comment by Quorum75** [comment]
Hi. I don't know if you are using Instagram but whatever I do it always breaks at sometime. Would you mind to look at it to make it working smoothly?  Thanks!

**Comment by Cybo1927** [comment]
I've been using for past 3 days and I have no problems, I'll try on a friends iPhone

**Comment by Quorum75** [comment]
> I've been using for past 3 days and I have no problems, I'll try on a friends iPhone

Hum... Instagram does not work if some domains are not white listed. I am very surprised from your answer. I had to add several domains and for some reasons sometimes I get no response: cannot post or cannot see a photo, or cannot send a message...

All the domains I had to allow:

i.instagram.com

graph.instagram.com

www.instagram.com

cdninstagram.com

z-p42-instagram.c10r.facebook.com

instagram.com

**Comment by Quorum75** [comment]
+crisp.chat

Allow Access to Live Support in Airmail application.

**Comment by Quorum75** [comment]
Since iOS 14 update something is blocking the download of applications from the Apple Store

**Comment by Cybo1927** [comment]
Sorry for the late response, school/other projects kinda made me forget about this

Working on the issues now

**Comment by Quorum75** [comment]
I guess you are not using enough iOS 😉 because many app and Apple processes are broken 😞

**Comment by Cybo1927** [comment]
I honestly don't know how to help, my iPad isn't broken and my friends iPhone has no problems using Blokada

I'd have to know domains to whitelist, I'll go through my hosts again and remove all Apple domains that I don't remember what they are

**Comment by Quorum75** [comment]
Your friend must have whilisted some Apple domains without telling you because for instance iOS update does not work (cf. My previous message). Same thing for Instagram and Tumblr. You can access these sites but you will not get the images and will face other issues..

**Comment by Quorum75** [comment]
+aexpfeedback.com

Allow American Express feedback

**Comment by Quorum75** [comment]
+feedback.airmailapp.com

Allow Airmail application testing feedback. 

https://apps.apple.com/us/app/airmail-your-mail-with-you/id993160329

**Comment by Quorum75** [comment]
+ guzzoni.apple.com
+ gsa.apple.com.akadns.net
+ su.itunes.apple.com

Allow Apple / iTunes to work properly

**Comment by Quorum75** [comment]
+bufferapp.com
Allow BUFFER app to work

https://apps.apple.com/us/app/buffer-social-media-manager/id490474324

**Comment by Quorum75** [comment]
+www.linkedin.com
+media-exp1.licdn.com

Allow LinkedIn app to work 

https://apps.apple.com/us/app/linkedin-network-job-finder/id288429040

**Comment by Quorum75** [comment]
+imap.mail.yahoo.com

Allow IMAP access to Yahoo email through you iOS email app.

**Comment by Quorum75** [comment]
+imap.gmail.com

Allow IMAP access to Gmail email through you iOS email app.

**Comment by Quorum75** [comment]
+dealer.spotify.com

Help Spotify iOS app to work properly

**Comment by Quorum75** [comment]
+officeclient.microsoft.com
+login.live.com

Allow Microsoft iOS app to work correctly

**Comment by Quorum75** [comment]
+oauth.reddit.com
+gql.reddit.com
+preview.redd.it
+gateway.reddit.com
+external-preview.redd.it
+v.redd.it

Allow iOS Reddit app to work correctly.

**Comment by Quorum75** [comment]
+pbs.twimg.com
+api.twitter.com 
+upload.twitter.com
+twitter.com

Allow Twitter iOS app to work correctly

**Comment by Quorum75** [comment]
+api.tumblr.com
+api-http2.tumblr.com
+media.tumblr.com

Allow Tumblr iOS app to work correctly

**Comment by Quorum75** [comment]
+api.msn.com

Allow access to MS News iOS app. 

https://apps.apple.com/us/app/microsoft-news/id945416273

**Comment by Cybo1927** [comment]
> aexpfeedback.com
> feedback.airmailapp.com
> guzzoni.apple.com
> gsa.apple.com.akadns.net
> su.itunes.apple.com
> bufferapp.com
> media-exp1.licdn.com
> imap.mail.yahoo.com
> imap.gmail.com
> dealer.spotify.com
> officeclient.microsoft.com
> login.live.com
> oauth.reddit.com
> gql.reddit.com
> preview.redd.it
> gateway.reddit.com
> external-preview.redd.it
> v.redd.it
> reddit.map.fastly.net
> pbs.twimg.com
> api.twitter.com
> upload.twitter.com
> twitter.com
> t.co
> api.tumblr.com
> api-http2.tumblr.com
> media.tumblr.com
> api.msn.com

Not a single one of these domains is blocked in hosts as far as I can tell, I've run them all through the search function in Github and tested on my iPad Mini 2, Pixel 3, Samsung Tablet, and my friends iPhone XR with none of these apps or domains having problems. Nothing is in his whitelist either.

**Comment by Quorum75** [comment]
Thanks for the feedback. I will keep these domains in my Allow List because on my side they look blocked. 

Did you check Apple domains? I have one blocked mesu.apple.com (used for software update) that I white listed. After some research I found this page that I found very useful to help you to white list the right Apple domains. 

https://support.apple.com/fr-fr/HT210060

**Comment by Cybo1927** [comment]
That is very helpful, thank you! I'll look into all this over the next couple of days and fix as soon as possible
