### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by Korkycat** [Cybo1927/Hosts#83]
I've been using(added) your host list in Ublock origin on Firefox for a couple of weeks with no real problems. However this morning I can no longer middle click on a link in say Google or any other link anywhere and have it open in a new tab. When I middle click nothing happens. I've checked a few things in Firefox but to no avail. However unselecting your host list in ublock origin and everything goes back to normal ie; I can middle click on links and have them open in a new tab. I'm wondering if it is JS Dom. Any help please.

**Comment by Cybo1927** [comment]
I will try to find a fix, but as of now I can't seem to reproduce this. I'm going to update my Hosts right now and remove some possible suspects, please let me know if this issue is fixed now. If this issue persists could you please send me the Google URL in which you're having problems?

**Comment by Korkycat** [comment]
Thank you, what you have done has worked. There wasn't one particular Google url that didn't work, it was all the Google search results, also links on the Newsnow website or any link on say a news website none of them would open with a middle click of my mouse. However whatever you have done has worked, so I'm happy and thanks for your hosts list which I like.

**Comment by Cybo1927** [comment]
I'm glad to hear it works! Thank you for reporting the issue!
