### ISSUE TITLE
[WHITELIST] - assets.adobedtm.com

### ISSUE THREAD

**Issue by bakerboy448** [Cybo1927/Hosts#84]
# Domain to be whitelisted/unblocked

* `assets.adobedtm.com`

## Where the blocked domain causes problems

* `https://secure.verizon.com/vzauth/UI/Login`

### Screenshot(s)
<details>

![image](https://user-images.githubusercontent.com/55419169/127705478-51b1b1f0-6046-474d-bd76-69817a323c0e.png)
![image](https://user-images.githubusercontent.com/55419169/127705501-24adabc8-e45c-4f81-b2ca-770413e43903.png)

**After Whitelisting the subject domain**
![image](https://user-images.githubusercontent.com/55419169/127705600-96862525-7a9c-451d-bd64-714a7cc724c0.png)
</details>

# Your setup
- **Browser:**
  -  Chrome 92.0.4515.107
- **Ad/content blocker:**
  -  PiHole

**Comment by Cybo1927** [comment]
It doesn't appear this is blocked by me? Though I still whitelisted it.

**Comment by bakerboy448** [comment]
Ah crap, yup my bad.

a bit too lax on my googling earlier


From Pihole for posterity
> Exact match for assets.adobedtm.com found in: - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt 

I'll open up an issue over on https://github.com/lightswitch05/hosts/issues/new

sorry bout that :D

**Comment by Cybo1927** [comment]
It's all good, thanks for creating the issue! This may help other's who use lists that incorrectly block this!

**Comment by bakerboy448** [comment]
Xref for posterity as well
https://github.com/lightswitch05/hosts/issues/295
