### ISSUE TITLE
[WHITELIST] Possible Problematic Domain Block Rules in DNS Hosts/Hosts

### ISSUE THREAD

**Issue by sr093906** [Cybo1927/Hosts#85]
# Domain to be whitelisted/unblocked

127.net
2mdn.net
2o7.net
4dsply.com
a-mo.net
aan.amazon.com
actonservice.com
adj.st
agacelebir.com
agkn.com
aimatch.com
airbrake.io
alb.reddit.com
amplitude.com
an.yandex.ru
apester.com
apmebf.com
appcast.io
art19.com
asadcdn.com
at-o.net
atdmt.com
ati-host.net
autopilothq.com
avantlink.com
awaps.yandex.ru
aweber.com
awin1.com
bam-x.com
bc0a.com
betrad.com
bfast.com
bi.medscape.com
blueconic.net
bluecore.com
bm23.com
boldchat.com
bp01.net
branch.io
brightedge.com
bronto.com
browser.pipe.aria.microsoft.com
bs.yandex.ru
btstatic.com
c1.microsoft.com
cbox.ws
cbsinteractive.com
cedexis.com
certona.net
chartbeat.com
chatango.com
chip.de
cision.com
cj.com
clients1.google.com
cloudfront-labs.amazonaws.com
cmp-cdn.ghostery.com
cohesionapps.com
com.com
comet.yahoo.com
commander1.com
config.uca.cloud.unity3d.com
confirmit.com
consensu.org
conviva.com
cookiebot.com
cookielaw.org
countess.twitch.tv
cpt.itv.com
cquotient.com
credomobile.com
crl.microsoft.com
crowdtwist.com
cts.businesswire.com
customer.io
customerevents.netflix.com
cxense.com
d.ghostery.com
dartsearch.net
datacaciques.com
dc.services.visualstudio.com
demdex.net
detectportal.firefox.com
developermedia.com
digidip.net
districtm.ca
dolphincdn.xyz
dotomi.com
doubleclick.net
dpbolvw.net
driftt.com
dynamicyield.com
dynatrace.com
e.reddit.com
eloqua.com
emjcd.com
en25.com
entitlements.jwplayer.com
eulerian.net
eultech.fnac.com
everesttech.net
evidon.com
evyy.net
ezoic.net
fabric.io
faktor.io
fe3.delivery.dsp.mp.microsoft.com.nsatc.net
feature.fm
fireflyengagement.com
flingo.tv
fonecta.fi
frog.wix.com
fs.microsoft.com
fundingchoicesmessages.google.com
fwmrm.net
gamehouse.com
gemius.pl
getadmiral.com
getdrip.com
gfe.nvidia.com
gfwsl.geforce.com
gg.google.com
gleam.io
goatcounter.com
googleadapis.l.google.com
googletagmanager.com
googletagservices.com
gotraffic.net
grabify.link
grade.market.yandex.ru
gravityrd-services.com
growth-pa.googleapis.com
hello.myfonts.net
hockeyapp.net
hostingprod.com
hs-scripts.com
hsforms.net
hubapi.com
humanpresence.app
ia.media-imdb.com
ichnaea-web.netflix.com
ichnaea.netflix.com
idealmedia.io
iesnare.com
igodigital.com
impactradius.com
imrworldwide.com
in.appcenter.ms
indexww.com
insnw.net
instana.io
intercom.com
intergi.com
investingchannel.com
ioam.de
iris.tv
izooto.com
jaleco.com
janrain.com
jdoqocy.com
jivox.com
js.sohu.com
jwpltx.com
kampyle.com
krxd.net
l2.io
leadpages.net
litix.io
livefyre.com
liveinternet.ru
liveperson.com
liveperson.net
lomadee.com
m.yap.yahoo.com
mailerlite.com
mailfoogae.appspot.com
marfeel.com
marinsm.com
mc.yandex.ru
mediaplex.com
mediavoice.com
meltwater.com
metok.sys.miui.com
micpn.com
mindtake.com
mixi.media
mmtro.com
mobile.pipe.aria.microsoft.com
moengage.com
mparticle.com
mplxtms.com
msh.amazon.co.uk
mxpnl.com
myvisualiq.net
myway.com
nanigans.com
nanovisor.io
newrelic.com
npttech.com
nr-data.net
ntv.io
nui.media
ojrq.net
omaze.com
omniture-ssl.walmart.com
onelink.me
ooyala.com
opinionstage.com
optanon.blob.core.windows.net
osimg.nbcuni.com
p.typekit.net
pardot.com
parkingcrew.net
parklogic.com
parsely.com
payeer.com
pendo.io
perfdrive.com
plausible.io
po.st
polldaddy.com
powr.io
ppcprotect.com
primis.tech
privacy-center.org
proxad.net
purch.com
redirectingat.com
refersion.com
res-x.com
researchnow.com
rezync.com
richrelevance.com
sail-horizon.com
sajari.com
salesloft.com
salesmanago.pl
sas.com
sascdn.com
scroll.com
search.services.mozilla.com
sedoparking.com
segment.com
segment.io
sendpulse.com
sendsay.ru
shareaholic.com
shareasale.com
sift.com
siftscience.com
singular.net
skimlinks.com
smartclip.net
snap.licdn.com
snrcdn.net
snssdk.com
stat24.com
staticxx.facebook.com
stats.gc.apple.com
stats.t-online.de
symcd.com
syndication.twimg.com
syndication.twitter.com
t.paypal.com
tagger.opecloud.com
tamgrt.com
tapresearch.com
tawk.to
tce.alicdn.com
tealium.com
techlab-cdn.com
thebrighttag.com
tinypass.com
tiqcdn.com
tkqlhce.com
trackjs.com
tradedoubler.com
trafic.ro
traq.li
trbo.com
tritondigital.com
trustarc.com
tvpage.com
ucweb.com
ultimedia.com
unid.go.com
untd.com
urbanairship.com
usabilla.com
usercentrics.eu
v.shopify.com
vi-serve.com
vidazoo.com
video-fa.scdn.co
videoplaza.tv
vilynx.com
vizury.com
vortex.hulu.com
widgets.trustedshops.com
wootric.com
wt-eu02.net
wurfl.io
www-google-analytics.l.google.com
www-googletagmanager.l.google.com
xg4ken.com
xlog-va.musical.ly
xp.apple.com
yabs.yandex.ru
zanox.com
zapr.in
zdbb.net
zer0day.ch
ziffdavis.com
zopim.com

## Where the blocked domain causes problems

please search in https://oisd.nl/excludes.php

**Comment by Cybo1927** [comment]
Thank you for letting me know about these domains. I will be investigating these domains shortly, making sure to test things myself and make sure the information is still correct. And once again sorry for my inactivity!
