### ISSUE TITLE
first-party not support by ADG Home

### ISSUE THREAD

**Issue by Piber0** [Cybo1927/Hosts#87]
Your lists are excellent however Adguard Home does not support `first-party` in these rules: `@@||192.168.*.*^$first-party` and `@@||127.0.0.*^$first-party`.

**Comment by Cybo1927** [comment]
I'm terribly sorry about how long it took me to reply to this issue. Thank you for reporting this, I'll have it fixed within the next 12 hours whenever I get free time.
