### ISSUE TITLE
[WHITELIST] | Rakuten.com

### ISSUE THREAD

**Issue by Piber0** [Cybo1927/Hosts#88]
# Domain to be whitelisted/unblocked

* `rakuten.com`

## Where the blocked domain causes problems

* `https://fr.shopping.rakuten.com`

# Your setup
- **Browser:**
  -LibreWolf 101.0.1-1
- **Ad/content blocker:**
  -uBlock Origin & Adguard Home

**Comment by Cybo1927** [comment]
Thanks! This has been removed!
