### ISSUE TITLE
[WHITELIST] | Powerbi.microsoft.com

### ISSUE THREAD

**Issue by Piber0** [Cybo1927/Hosts#89]
# Domain to be whitelisted/unblocked

* `powerbi.microsoft.com`

## Where the blocked domain causes problems

* `https://powerbi.microsoft.com`

# Your setup
- **Browser:**
  -LibreWolf 101.0.1-1
- **Ad/content blocker:**
  -uBlock Origin & Adguard Home

**Comment by Cybo1927** [comment]
This is an analytics service run by Microsoft. Why should I whitelist it?

**Comment by Piber0** [comment]
Yeah, it's my bad, keep it on the blacklist.
